package cn.piesat.exam.domain;

public class PerformRules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perform_rules.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perform_rules.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perform_rules.kpi
     *
     * @mbg.generated
     */
    private String kpi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perform_rules.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perform_rules.rules
     *
     * @mbg.generated
     */
    private String rules;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perform_rules.id
     *
     * @return the value of perform_rules.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perform_rules.id
     *
     * @param id the value for perform_rules.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perform_rules.type
     *
     * @return the value of perform_rules.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perform_rules.type
     *
     * @param type the value for perform_rules.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perform_rules.kpi
     *
     * @return the value of perform_rules.kpi
     *
     * @mbg.generated
     */
    public String getKpi() {
        return kpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perform_rules.kpi
     *
     * @param kpi the value for perform_rules.kpi
     *
     * @mbg.generated
     */
    public void setKpi(String kpi) {
        this.kpi = kpi == null ? null : kpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perform_rules.weight
     *
     * @return the value of perform_rules.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perform_rules.weight
     *
     * @param weight the value for perform_rules.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perform_rules.rules
     *
     * @return the value of perform_rules.rules
     *
     * @mbg.generated
     */
    public String getRules() {
        return rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perform_rules.rules
     *
     * @param rules the value for perform_rules.rules
     *
     * @mbg.generated
     */
    public void setRules(String rules) {
        this.rules = rules == null ? null : rules.trim();
    }
}